# Generated by Django 4.2.24 on 2026-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="agencies/logos/", verbose_name="Логотип"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="agencies/covers/", verbose_name="Обложка"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Верифицировано"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Агентство",
                "verbose_name_plural": "Агентства",
                "ordering": ["-rating", "name"],
            },
        ),
    ]
