# Generated by Django 4.2.24 on 2026-01-18 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail-Adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefonnummer"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geburtsdatum"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Straße und Hausnummer"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Postleitzahl"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Stadt"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("DE", "Deutschland"), ("AT", "Österreich")],
                        default="DE",
                        max_length=2,
                        verbose_name="Land",
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Versichertennummer"
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Krankenkasse"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")],
                        default="de",
                        max_length=2,
                        verbose_name="Sprache",
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(default=False, verbose_name="AGB akzeptiert"),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AGB akzeptiert am"
                    ),
                ),
                (
                    "privacy_accepted",
                    models.BooleanField(
                        default=False, verbose_name="Datenschutz akzeptiert"
                    ),
                ),
                (
                    "privacy_accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Datenschutz akzeptiert am"
                    ),
                ),
                (
                    "medical_data_consent",
                    models.BooleanField(
                        default=False, verbose_name="Einwilligung Gesundheitsdaten"
                    ),
                ),
                (
                    "medical_data_consent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Einwilligung Gesundheitsdaten am",
                    ),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(
                        default=False, verbose_name="Marketing-Einwilligung"
                    ),
                ),
                (
                    "marketing_consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Marketing-Einwilligung am"
                    ),
                ),
                (
                    "data_processing_consent",
                    models.BooleanField(
                        default=False, verbose_name="Einwilligung zur Datenverarbeitung"
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "paypal_payer_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="PayPal Payer ID"
                    ),
                ),
                (
                    "onboarding_step",
                    models.IntegerField(
                        choices=[
                            (1, "Profil ausfüllen"),
                            (2, "Dokumente hochladen"),
                            (3, "Tarif wählen"),
                            (4, "Zahlung einrichten"),
                            (5, "Abgeschlossen"),
                        ],
                        default=1,
                        verbose_name="Onboarding-Schritt",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, verbose_name="Onboarding abgeschlossen"
                    ),
                ),
                (
                    "documents_verified",
                    models.BooleanField(
                        default=False, verbose_name="Dokumente geprüft"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer",
                "verbose_name_plural": "Benutzer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Rezept"),
                            ("insurance_card", "Versichertenkarte"),
                            ("id_document", "Ausweisdokument"),
                            ("other", "Sonstiges"),
                        ],
                        default="prescription",
                        max_length=20,
                        verbose_name="Dokumenttyp",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="Datei"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Originaldateiname"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Überprüft am"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Ablehnungsgrund"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("medical_data", "Medizinische Daten (Art. 9 DSGVO)"),
                            ("terms", "AGB"),
                            ("privacy", "Datenschutzerklärung"),
                            ("marketing", "Marketing"),
                            ("cookies_functional", "Funktionale Cookies"),
                            ("cookies_analytics", "Analyse-Cookies"),
                        ],
                        max_length=30,
                        verbose_name="Art der Einwilligung",
                    ),
                ),
                ("granted", models.BooleanField(default=True, verbose_name="Erteilt")),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0",
                        max_length=20,
                        verbose_name="Version der Einwilligung",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "consent_text_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash для проверки изменений текста",
                        max_length=64,
                        verbose_name="Hash des Einwilligungstexts",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erteilt am"),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Widerrufen am"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einwilligungsprotokoll",
                "verbose_name_plural": "Einwilligungsprotokolle",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="accounts_co_user_id_971819_idx",
                    ),
                    models.Index(
                        fields=["consent_type", "created_at"],
                        name="accounts_co_consent_4e4edb_idx",
                    ),
                ],
            },
        ),
    ]
