# Generated by Django 4.2.24 on 2026-01-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="userdocument",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="data_processing_consent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="documents_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="insurance_company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="insurance_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="language",
        ),
        migrations.RemoveField(
            model_name="user",
            name="marketing_consent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="marketing_consent_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="medical_data_consent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="medical_data_consent_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="onboarding_completed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="onboarding_step",
        ),
        migrations.RemoveField(
            model_name="user",
            name="paypal_payer_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="privacy_accepted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="privacy_accepted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="street",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="terms_accepted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="terms_accepted_at",
        ),
        migrations.AddField(
            model_name="user",
            name="is_investor",
            field=models.BooleanField(default=False, verbose_name="Инвестор"),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=100, verbose_name="Telegram"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="ConsentLog",
        ),
        migrations.DeleteModel(
            name="UserDocument",
        ),
    ]
