# Generated by Django 4.2.27 on 2026-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="events/", verbose_name="Изображение"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Полное описание (HTML)"),
                ),
                ("event_date", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(max_length=100, verbose_name="Место"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Полный адрес"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, verbose_name="Ссылка на регистрацию"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Предстоящее"),
                            ("ongoing", "Идёт сейчас"),
                            ("completed", "Завершено"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="На главной"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-event_date"],
            },
        ),
    ]
