# Generated by Django 4.2.24 on 2026-01-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("developers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="properties/", verbose_name="Главное фото"
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена от ($)",
                    ),
                ),
                (
                    "area",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Площадь (м²)"
                    ),
                ),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Комнат"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sale", "Продажа"),
                            ("presale", "Предпродажа"),
                            ("sold", "Продано"),
                        ],
                        default="sale",
                        max_length=20,
                        verbose_name="Статус продажи",
                    ),
                ),
                (
                    "construction_status",
                    models.CharField(
                        choices=[
                            ("completed", "Сдан"),
                            ("in_progress", "Строится"),
                            ("planned", "Планируется"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус строительства",
                    ),
                ),
                (
                    "completion_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Дата сдачи"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Полное описание (HTML)"),
                ),
                (
                    "roi_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="ROI %",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемый"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="developers.developer",
                        verbose_name="Застройщик",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="properties.location",
                        verbose_name="Локация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Тип недвижимости",
                "verbose_name_plural": "Типы недвижимости",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="properties/gallery/", verbose_name="Фото"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото объекта",
                "verbose_name_plural": "Фото объектов",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="properties.propertytype",
                verbose_name="Тип",
            ),
        ),
    ]
