# Generated by Django 4.2.27 on 2026-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_airport",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="До аэропорта"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_beach",
            field=models.CharField(blank=True, max_length=20, verbose_name="До пляжа"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_cafe",
            field=models.CharField(blank=True, max_length=20, verbose_name="До кафе"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_center",
            field=models.CharField(blank=True, max_length=20, verbose_name="До центра"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_clinic",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="До клиники"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_gym",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="До спортзала"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_park",
            field=models.CharField(blank=True, max_length=20, verbose_name="До парка"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_pharmacy",
            field=models.CharField(blank=True, max_length=20, verbose_name="До аптеки"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_school",
            field=models.CharField(blank=True, max_length=20, verbose_name="До школы"),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_shopping",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="До магазинов"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_supermarket",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="До супермаркета"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_garage",
            field=models.BooleanField(default=False, verbose_name="Гараж"),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ocean_distance",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Расстояние до океана"
            ),
        ),
    ]
