# Generated by Django 4.2.27 on 2026-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_address_property_distance_airport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="main_image_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Или ссылка на главное фото"
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Или ссылка на фото"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="properties/",
                verbose_name="Главное фото",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="properties/gallery/",
                verbose_name="Фото",
            ),
        ),
    ]
