# Generated by Django 4.2.24 on 2025-12-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog-Kategorie",
                "verbose_name_plural": "Blog-Kategorien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Kurze Beschreibung für Vorschau (max 500 Zeichen)",
                        max_length=500,
                        verbose_name="Kurzbeschreibung",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Empfohlen: 832x832px",
                        upload_to="blog/%Y/%m/",
                        verbose_name="Beitragsbild",
                    ),
                ),
                ("content", models.TextField(verbose_name="Inhalt")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("published", "Veröffentlicht")],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Kommagetrennte Tags, z.B.: Medikamente, Gesundheit, Tipps",
                        max_length=255,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Meta-Titel"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta-Beschreibung"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Veröffentlicht am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog-Beitrag",
                "verbose_name_plural": "Blog-Beiträge",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
