# Generated by Django 4.2.24 on 2026-01-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.blogcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Контент (HTML)"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(max_length=500, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                upload_to="blog/%Y/%m/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta Description"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=70, verbose_name="Meta Title"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
