# Generated by Django 4.2.24 on 2026-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogcategory_options_alter_blogpost_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="featured_image_url",
            field=models.URLField(
                blank=True,
                help_text="Внешняя ссылка на изображение (если не загружаете файл)",
                max_length=500,
                verbose_name="Или ссылка на изображение",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендуемый размер: 832x832px",
                null=True,
                upload_to="blog/%Y/%m/",
                verbose_name="Изображение",
            ),
        ),
    ]
