# Generated by Django 4.2.24 on 2026-01-18 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="developers/logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="developers/covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Полное описание (HTML)"),
                ),
                (
                    "completed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сдано объектов"
                    ),
                ),
                (
                    "in_progress_count",
                    models.PositiveIntegerField(default=0, verbose_name="Строится"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        verbose_name="Общий рейтинг",
                    ),
                ),
                (
                    "premium_rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Премиальность"
                    ),
                ),
                (
                    "support_rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Поддержка"
                    ),
                ),
                (
                    "quality_rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Качество"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Верифицирован"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Застройщик",
                "verbose_name_plural": "Застройщики",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Иконка (URL)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Категория девелоперов",
                "verbose_name_plural": "Категории девелоперов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "user_avatar",
                    models.ImageField(
                        blank=True, upload_to="reviews/avatars/", verbose_name="Аватар"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Одобрен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="developers.developer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="developer",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developers",
                to="developers.developercategory",
            ),
        ),
    ]
