# Generated by Django 4.2.24 on 2026-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developerreview",
            name="user_avatar_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Или ссылка на аватар"
            ),
        ),
    ]
