# Generated by Django 4.2.27 on 2026-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0002_developerreview_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="short_description_for_property",
            field=models.TextField(
                blank=True,
                help_text="Для карточки на странице объекта",
                max_length=300,
                verbose_name="Краткое описание",
            ),
        ),
    ]
