# Generated by Django 4.2.27 on 2026-01-31 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0003_developer_short_description_for_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Год основания"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="innovations",
            field=models.TextField(
                blank=True, verbose_name="Инновации и устойчивое развитие"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="rating_deadline",
            field=models.PositiveSmallIntegerField(
                default=80, verbose_name="Рейтинг: Срок сдачи (%)"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="rating_premium",
            field=models.PositiveSmallIntegerField(
                default=80, verbose_name="Рейтинг: Премиальность (%)"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="rating_quality",
            field=models.PositiveSmallIntegerField(
                default=80, verbose_name="Рейтинг: Качество (%)"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="rating_support",
            field=models.PositiveSmallIntegerField(
                default=80, verbose_name="Рейтинг: Поддержка (%)"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="services",
            field=models.TextField(blank=True, verbose_name="Сервис и философия"),
        ),
        migrations.AddField(
            model_name="developer",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Например: Бутик-девелопер и управляющая компания",
                max_length=255,
                verbose_name="Слоган/тип компании",
            ),
        ),
        migrations.CreateModel(
            name="DeveloperHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Текст")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="developers.developer",
                        verbose_name="Застройщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order"],
            },
        ),
    ]
