# Generated by Django 4.2.27 on 2026-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0004_developer_founded_year_developer_innovations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="in_progress_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Строится объектов"
            ),
        ),
    ]
