# Generated by Django 4.2.27 on 2026-02-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Для себя, например: Google Analytics",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "code",
                    models.TextField(help_text="HTML, JS, CSS код", verbose_name="Код"),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head", "Head (перед </head>)"),
                            ("body_start", "Body Start (после <body>)"),
                            ("body_end", "Body End (перед </body>)"),
                        ],
                        default="head",
                        max_length=20,
                        verbose_name="Расположение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сниппет кода",
                "verbose_name_plural": "Сниппеты кода",
                "ordering": ["location", "order"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Источник"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Вопрос-ответ",
                "verbose_name_plural": "Вопросы и ответы",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Popup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название (для админки)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Используется в data-popup='#popup-{slug}'",
                        unique=True,
                        verbose_name="Код popup",
                    ),
                ),
                (
                    "logo_left",
                    models.ImageField(
                        blank=True, upload_to="popups/", verbose_name="Логотип слева"
                    ),
                ),
                (
                    "logo_left_url",
                    models.URLField(blank=True, verbose_name="Или URL логотипа слева"),
                ),
                (
                    "logo_right",
                    models.ImageField(
                        blank=True, upload_to="popups/", verbose_name="Логотип справа"
                    ),
                ),
                (
                    "logo_right_url",
                    models.URLField(blank=True, verbose_name="Или URL логотипа справа"),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Например: До 31 декабря!",
                        max_length=50,
                        verbose_name="Текст бейджа",
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="#BFFF00", max_length=20, verbose_name="Цвет бейджа"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_highlight",
                    models.CharField(
                        blank=True,
                        help_text="Эта часть будет жирной",
                        max_length=255,
                        verbose_name="Выделенная часть заголовка",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, upload_to="popups/", verbose_name="Фоновая картинка"
                    ),
                ),
                (
                    "background_image_url",
                    models.URLField(blank=True, verbose_name="Или URL фона"),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#1a1a2e", max_length=20, verbose_name="Цвет фона"
                    ),
                ),
                (
                    "input_placeholder",
                    models.CharField(
                        default="Введите Ваш WhatsApp",
                        max_length=100,
                        verbose_name="Placeholder поля ввода",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Получить консультацию",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        default="#BFFF00", max_length=20, verbose_name="Цвет кнопки"
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram Bot Token"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telegram Chat ID"
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email для уведомлений"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Popup окно",
                "verbose_name_plural": "Popup окна",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="О нас",
                        max_length=200,
                        verbose_name="Заголовок секции О нас",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(blank=True, verbose_name="Текст О нас (HTML)"),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="espacademia",
                        max_length=100,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@espacademia.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "contact_address",
                    models.CharField(
                        default="Бали, Индонезия", max_length=255, verbose_name="Адрес"
                    ),
                ),
                (
                    "telegram_link",
                    models.URLField(
                        blank=True,
                        default="https://t.me/espacademia",
                        verbose_name="Telegram",
                    ),
                ),
                ("whatsapp_link", models.URLField(blank=True, verbose_name="WhatsApp")),
                (
                    "instagram_link",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_link", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "meta_title",
                    models.CharField(
                        default="espacademia - Рейтинг застройщиков Бали",
                        max_length=70,
                        verbose_name="Meta Title главной",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Независимый рейтинг застройщиков на Бали",
                        max_length=160,
                        verbose_name="Meta Description главной",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="HeaderButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название кнопки"),
                ),
                (
                    "button_text",
                    models.CharField(max_length=100, verbose_name="Текст на кнопке"),
                ),
                ("link", models.URLField(blank=True, verbose_name="Или ссылка")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header_main", "Header основная"),
                            ("header_mobile", "Header мобильная"),
                        ],
                        default="header_main",
                        max_length=20,
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "popup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="header_buttons",
                        to="core.popup",
                        verbose_name="Popup окно",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка Header",
                "verbose_name_plural": "Кнопки Header",
                "ordering": ["position", "order"],
            },
        ),
    ]
