# Generated by Django 4.2.27 on 2026-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "user_avatar",
                    models.ImageField(
                        blank=True, upload_to="reviews/", verbose_name="Аватар (файл)"
                    ),
                ),
                (
                    "user_avatar_url",
                    models.URLField(blank=True, verbose_name="Или URL аватара"),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5, help_text="От 1 до 5", verbose_name="Рейтинг"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
