# Generated by Django 4.2.27 on 2026-02-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="course_name",
            field=models.CharField(
                blank=True,
                help_text="Например: Курс А1, Курс B2",
                max_length=100,
                verbose_name="Курс",
            ),
        ),
    ]
