# Generated by Django 4.2.24 on 2026-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="О нас",
                        max_length=200,
                        verbose_name="Заголовок секции О нас",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(blank=True, verbose_name="Текст О нас (HTML)"),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="espacademia",
                        max_length=100,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@espacademia.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "contact_address",
                    models.CharField(
                        default="Бали, Индонезия", max_length=255, verbose_name="Адрес"
                    ),
                ),
                (
                    "telegram_link",
                    models.URLField(
                        blank=True,
                        default="https://t.me/espacademia",
                        verbose_name="Telegram",
                    ),
                ),
                ("whatsapp_link", models.URLField(blank=True, verbose_name="WhatsApp")),
                (
                    "instagram_link",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_link", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "meta_title",
                    models.CharField(
                        default="espacademia - Рейтинг застройщиков Бали",
                        max_length=70,
                        verbose_name="Meta Title главной",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Независимый рейтинг застройщиков на Бали",
                        max_length=160,
                        verbose_name="Meta Description главной",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
