# Generated by Django 4.2.27 on 2026-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review_course_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhySpanishItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=10, verbose_name="Эмодзи"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Изображение"), ("video", "Видео")],
                        default="image",
                        max_length=5,
                        verbose_name="Тип медиа",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="why_spanish/", verbose_name="Изображение"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на видео (YouTube)"
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        upload_to="why_spanish/posters/",
                        verbose_name="Обложка видео",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Преимущество испанского",
                "verbose_name_plural": "Преимущества испанского",
                "ordering": ["order"],
            },
        ),
    ]
