# Generated by Django 4.2.24 on 2026-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_url_external",
            field=models.URLField(
                blank=True,
                help_text="Или вставьте ссылку на изображение. Пример: https://img.youtube.com/vi/W7uANluGQSY/maxresdefault.jpg",
                verbose_name="Превью (ссылка)",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to="videos/", verbose_name="Превью (файл)"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(
                help_text="ID из ссылки YouTube. Пример: для https://www.youtube.com/watch?v=W7uANluGQSY&t=2s введите: W7uANluGQSY",
                max_length=20,
                verbose_name="YouTube ID",
            ),
        ),
    ]
