# Generated by Django 4.2.24 on 2026-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_video_thumbnail_url_external_alter_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Google Analytics",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                ("code", models.TextField(help_text="HTML/JS код", verbose_name="Код")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head", "В <head>"),
                            ("body_start", "После <body>"),
                            ("body_end", "Перед </body>"),
                        ],
                        default="head",
                        max_length=20,
                        verbose_name="Расположение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Меньше = раньше",
                        verbose_name="Приоритет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сниппет кода",
                "verbose_name_plural": "Сниппеты кода",
                "ordering": ["location", "priority"],
            },
        ),
    ]
