# Generated by Django 4.2.27 on 2026-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_video_thumbnail_url_external_alter_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Для себя, например: Google Analytics",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "code",
                    models.TextField(help_text="HTML, JS, CSS код", verbose_name="Код"),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head", "Head (перед </head>)"),
                            ("body_start", "Body Start (после <body>)"),
                            ("body_end", "Body End (перед </body>)"),
                        ],
                        default="head",
                        max_length=20,
                        verbose_name="Расположение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сниппет кода",
                "verbose_name_plural": "Сниппеты кода",
                "ordering": ["location", "order"],
            },
        ),
    ]
