# Generated by Django 4.2.27 on 2026-02-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_whyspanishitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "user_avatar",
                    models.ImageField(
                        blank=True,
                        upload_to="video_reviews/",
                        verbose_name="Аватар (файл)",
                    ),
                ),
                (
                    "user_avatar_url",
                    models.URLField(blank=True, verbose_name="Или URL аватара"),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True,
                        help_text="Например: Курс А1",
                        max_length=100,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(verbose_name="Ссылка на YouTube видео"),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        upload_to="video_reviews/posters/",
                        verbose_name="Обложка (если нет — возьмётся с YouTube)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Видео-отзыв",
                "verbose_name_plural": "Видео-отзывы",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
