# Generated by Django 4.2.27 on 2026-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_videoreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoreview",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("all", "Все страницы"),
                    ("activo", "Español Activo"),
                    ("intensivo", "Español Activo Intensivo"),
                    ("club", "Разговорный клуб"),
                    ("kids", "Для детей"),
                    ("individual", "Индивидуальные занятия"),
                    ("dele", "Подготовка к DELE"),
                ],
                default="all",
                help_text="На какой странице курса показывать",
                max_length=20,
                verbose_name="Тип курса",
            ),
        ),
    ]
