# Generated by Django 4.2.27 on 2026-02-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0005_alter_developer_in_progress_count"),
        ("core", "0005_codesnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("banner_top", "Верхний баннер (с табами)"),
                            ("banner_middle1", "Средний баннер 1"),
                            ("banner_middle2", "Средний баннер 2"),
                            ("sidebar", "Сайдбар"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Место размещения",
                "verbose_name_plural": "Места размещения",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название (для админки)"
                    ),
                ),
                (
                    "image_desktop",
                    models.ImageField(
                        blank=True,
                        upload_to="banners/desktop/",
                        verbose_name="Изображение Desktop",
                    ),
                ),
                (
                    "image_desktop_url",
                    models.URLField(
                        blank=True,
                        help_text="Внешняя ссылка на изображение (если не загружаете файл)",
                        verbose_name="Или URL Desktop",
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        upload_to="banners/mobile/",
                        verbose_name="Изображение Mobile",
                    ),
                ),
                (
                    "image_mobile_url",
                    models.URLField(
                        blank=True,
                        help_text="Внешняя ссылка на мобильное изображение",
                        verbose_name="Или URL Mobile",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Ссылка при клике")),
                (
                    "open_popup",
                    models.BooleanField(
                        default=True,
                        help_text="Если включено, при клике откроется форма заявки вместо перехода по ссылке",
                        verbose_name="Открывать popup заявки",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        default="Баннер", max_length=255, verbose_name="Alt текст"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "developer_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Только для верхнего баннера с табами",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banners",
                        to="developers.developercategory",
                        verbose_name="Категория девелоперов",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="core.bannerplacement",
                        verbose_name="Место размещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "ordering": ["placement", "order"],
            },
        ),
    ]
