# Generated by Django 4.2.27 on 2026-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_videoreview_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_address",
            field=models.CharField(
                default="Москва, Россия", max_length=255, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description",
            field=models.CharField(
                default="Онлайн школа испанского с носителями от А1 до С1. Заговорите за 3 месяца!",
                max_length=160,
                verbose_name="Meta Description главной",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_title",
            field=models.CharField(
                default="Онлайн курсы испанского языка — ESPacademia",
                max_length=70,
                verbose_name="Meta Title главной",
            ),
        ),
    ]
