# Generated by Django 4.2.27 on 2026-02-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_bannerplacement_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="partners/", verbose_name="Логотип (файл)"
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, verbose_name="Или URL логотипа"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Сайт партнера")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "ordering": ["order", "name"],
            },
        ),
    ]
