# Generated by Django 4.2.27 on 2026-02-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Popup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название (для админки)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Используется в data-popup='#popup-{slug}'",
                        unique=True,
                        verbose_name="Код popup",
                    ),
                ),
                (
                    "logo_left",
                    models.ImageField(
                        blank=True, upload_to="popups/", verbose_name="Логотип слева"
                    ),
                ),
                (
                    "logo_left_url",
                    models.URLField(blank=True, verbose_name="Или URL логотипа слева"),
                ),
                (
                    "logo_right",
                    models.ImageField(
                        blank=True, upload_to="popups/", verbose_name="Логотип справа"
                    ),
                ),
                (
                    "logo_right_url",
                    models.URLField(blank=True, verbose_name="Или URL логотипа справа"),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Например: До 31 декабря!",
                        max_length=50,
                        verbose_name="Текст бейджа",
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="#BFFF00", max_length=20, verbose_name="Цвет бейджа"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_highlight",
                    models.CharField(
                        blank=True,
                        help_text="Эта часть будет жирной",
                        max_length=255,
                        verbose_name="Выделенная часть заголовка",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, upload_to="popups/", verbose_name="Фоновая картинка"
                    ),
                ),
                (
                    "background_image_url",
                    models.URLField(blank=True, verbose_name="Или URL фона"),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#1a1a2e", max_length=20, verbose_name="Цвет фона"
                    ),
                ),
                (
                    "input_placeholder",
                    models.CharField(
                        default="Введите Ваш WhatsApp",
                        max_length=100,
                        verbose_name="Placeholder поля ввода",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Получить консультацию",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        default="#BFFF00", max_length=20, verbose_name="Цвет кнопки"
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram Bot Token"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telegram Chat ID"
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email для уведомлений"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Popup окно",
                "verbose_name_plural": "Popup окна",
            },
        ),
        migrations.CreateModel(
            name="HeaderButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название кнопки"),
                ),
                (
                    "button_text",
                    models.CharField(max_length=100, verbose_name="Текст на кнопке"),
                ),
                ("link", models.URLField(blank=True, verbose_name="Или ссылка")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header_main", "Header основная"),
                            ("header_mobile", "Header мобильная"),
                        ],
                        default="header_main",
                        max_length=20,
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "popup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="header_buttons",
                        to="core.popup",
                        verbose_name="Popup окно",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка Header",
                "verbose_name_plural": "Кнопки Header",
                "ordering": ["position", "order"],
            },
        ),
        migrations.AddField(
            model_name="banner",
            name="popup",
            field=models.ForeignKey(
                blank=True,
                help_text="Кастомный popup при клике (вместо стандартного)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banners",
                to="core.popup",
                verbose_name="Popup окно",
            ),
        ),
    ]
